/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Corvette2.glb 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from './src/context/Customization';
import { state } from './src/components/ColorPicker';

export function Corvette(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Corvette2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.plate.geometry} material={materials.plate} />
      <mesh geometry={nodes.Blinker_Border_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Blinker_Border_Inside_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Chrome_Bump_Headlight_0.geometry} material={materials.Bump_Headlight} />
      <mesh geometry={nodes.Glass_Glass_Light_0.geometry} material={materials.Glass_Light} />
      <mesh geometry={nodes.A_Pillar_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.MainBody.geometry} material={materials.BaseMtl} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.MainBody002.geometry} material={materials['Slaughter.001']} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.MainBody003.geometry} material={materials.BatLady} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.MainBody004.geometry} material={materials.BrakeLine} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.MainBody005.geometry} material={materials.Embers} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.MainBody006.geometry} material={materials['SpiderID.001']} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.MainBody007.geometry} material={materials.Fluid} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.MainBody008.geometry} material={materials.HotRod} position={[0, -0.059, 0]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.MainBody009.geometry} material={materials['Mayan.001']} position={[0, -0.059, -0.005]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.MainBody010.geometry} material={materials['SeaBreeze.001']} position={[0.003, -0.059, -0.017]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.MainBody011.geometry} material={materials['ShapeShifter.001']} position={[0.003, -0.059, -0.017]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.MainBody012.geometry} material={materials['Silk.001']} position={[0.003, -0.073, 0.015]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.MainBody013.geometry} material={materials['SnakeSkin.001']} position={[0.003, -0.073, 0.015]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.MainBody014.geometry} material={materials.Flare} position={[0.003, -0.073, 0.015]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.MainBody015.geometry} material={materials.Dominator} position={[0.003, -0.073, 0.015]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.MainBody016.geometry} material={materials['TopGun.001']} position={[0.003, -0.073, 0.01]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.MainBody017.geometry} material={materials.Explosion} position={[0.003, -0.073, 0.01]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.MainBody018.geometry} material={materials['WildWest.001']} position={[0.003, -0.073, 0.01]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.MainBody019.geometry} material={materials.Zombie} position={[0.003, -0.073, 0.01]} rotation={[-Math.PI / 2, 0, 0]} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.MainBody020.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Mirror_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Mirror_Chrome_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Roof_Black_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Side_Intake_Black_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Fender_Extension_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Side_Skirt_Extra_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Splitter_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Splitter_Sides_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Corvette_Text_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Chrome_Parts001_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag001_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black001_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red001_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump001_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Chrome_Parts_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Bottom_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Front_Mud_Flap_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Intake_Shadow_Planes_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Mud_Flaps_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Mud_Flaps_Black_0001.geometry} material={materials.Black} />
      <mesh geometry={nodes.Diffuser001_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Diffuser_Vent_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Diffuser_Vent_Border_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Exhaust_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Exhaust_Border_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Licence_Plate_Plate_0.geometry} material={materials.Plate} />
      <mesh geometry={nodes.Chrome_Bump_Bump_Headlight_0.geometry} material={materials.Bump_Headlight} />
      <mesh geometry={nodes.Extra_Details_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Headlight_Cover_Glass_Light_0.geometry} material={materials.Glass_Light} />
      <mesh geometry={nodes.Headlight_Housing_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Led_Glass_Led_Glass_0.geometry} material={materials.Led_Glass} />
      <mesh geometry={nodes.Led_Housing_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Lens_Headlight_Lens_0.geometry} material={materials.Headlight_Lens} />
      <mesh geometry={nodes.Lens_Housing_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Light_Source001_Light_Source_0.geometry} material={materials.Light_Source} />
      <mesh geometry={nodes.Top_Detail_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Top_Glass_Glass_Light_0.geometry} material={materials.Glass_Light} />
      <mesh geometry={nodes.Fender_Housing_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Intake_Vent_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Z06_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z06_Right_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z_Z06_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Z_Z06_Right_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Grille_Border_Metallic_Black_0_1.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Grille_Border_Metallic_Black_0_2.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Grille_Border_Metallic_Black_0_3.geometry} material={materials.Black} />
      <mesh geometry={nodes.Grille_Border_Metallic_Black_0_4.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Intercooler_Intercooler_0.geometry} material={materials.Intercooler} />
      <mesh geometry={nodes.Hood_Diamond_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Hood_Diamond_Metallic_Black_0001.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Hood_Diamond_Metallic_Black_0002.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Hood_Housing_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Hood_Intake_Grille_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Diamond_Mesh_Fender_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Shoulder_Vent_Border_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Shoulder_Vent_Border001_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Seats_and_Rest_mat_0_Interior_0.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Seats_and_Rest_mat_0_Interior_0001.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Seats_and_Rest_mat_2_Interior_0.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Shell_mat_0_Interior_0.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Shell_mat_0_Interior_0001.geometry} material={materials.Interior} />
      <mesh geometry={nodes.D_Bump_Bump_Reflectors_0.geometry} material={materials.Bump_Reflectors} />
      <mesh geometry={nodes.D_Chrome_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.D_Glass_Red_Glass_0.geometry} material={materials.Red_Glass} />
      <mesh geometry={nodes.F_Bump_Bump_Reflectors_0.geometry} material={materials.Bump_Reflectors} />
      <mesh geometry={nodes.F_Chrome_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.F_Glass_Blinker_Orange_0.geometry} material={materials.Blinker_Orange} />
      <mesh geometry={nodes.F_Light_Source_Light_Source_0.geometry} material={materials.Light_Source} />
      <mesh geometry={nodes.T_Bump_Bump_Reflectors_0.geometry} material={materials.Bump_Reflectors} />
      <mesh geometry={nodes.T_Chrome_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.T_Glass_Blinker_Orange_0.geometry} material={materials.Blinker_Orange} />
      <mesh geometry={nodes.T_Light_Source_Light_Source_0.geometry} material={materials.Light_Source} />
      <mesh geometry={nodes['Brake-Light_Housing_Metallic_Black_0'].geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Brake_Light_Glass_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Chrome_Details_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Dark_Outer_Line_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Spoiler_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Spoiler_Glass_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Spoiler_Screws_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Tube_Light_Source_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Bridge_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Light_Source_R_Light_Source_0.geometry} material={materials.Light_Source} />
      <mesh geometry={nodes.Taillight_Bump_Bump_Taillight_0.geometry} material={materials.Bump_Taillight} />
      <mesh geometry={nodes.Taillight_Chrome_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Taillight_Chrome_Lines_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Taillight_Diamond_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Taillight_Diamond_Outer_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Taillight_Glass_Red_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Taillight_Housing_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Taillight_Top_Glass_Bump_Bump_Taillight_Glass_0.geometry} material={materials.Bump_Taillight_Glass} />
      <mesh geometry={nodes.Taillight_Vents_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Chrome_Parts002_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag002_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black002_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red002_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump002_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Brake_Pad_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Brake_Pad_Holder_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Caliper_Nuts_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Caliper_Screws_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Brake_Disc_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Connection_Part_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Screws_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws_Aluminium_0001.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws_Holder_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Air_Stem_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Middle_Cap_1_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Middle_Cap_2_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Wheel_Nut_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z06_Rim_mat_1_Corvette_Yellow_0.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Chrome_Parts005_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag005_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black005_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red005_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump005_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Brake_Pad003_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Brake_Pad_Holder003_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Caliper_Nuts003_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Caliper_Screws003_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Brake_Disc003_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Connection_Part003_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Screws003_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws003_Aluminium_0001.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws_Holder003_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Air_Stem002_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Middle_Cap_1003_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Middle_Cap_2003_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Wheel_Nut003_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z06_Rim001_mat_1_Corvette_Yellow_0.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Chrome_Parts003_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag003_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black003_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red003_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump003_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Brake_Pad001_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Brake_Pad_Holder001_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Caliper001_Caliper_0_1.geometry} material={materials.Caliper} />
      <mesh geometry={nodes.Caliper001_Caliper_0_2.geometry} material={materials.Tire} />
      <mesh geometry={nodes.Caliper001_Caliper_0_3.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Caliper_Nuts001_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Caliper_Screws001_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Brake_Disc001_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Connection_Part001_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Screws001_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws001_Aluminium_0001.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws_Holder001_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Air_Stem001_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Middle_Cap_1001_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Middle_Cap_2001_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Wheel_Nut001_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z06_Rim005_mat_1_Corvette_Yellow_0.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Chrome_Parts004_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Flag004_Amblem_White_0.geometry} material={materials.Amblem_White} />
      <mesh geometry={nodes.Lines_Black004_Amblem_Black_0.geometry} material={materials.Amblem_Black} />
      <mesh geometry={nodes.Lines_Red004_Amblem_Red_0.geometry} material={materials.Amblem_Red} />
      <mesh geometry={nodes.Logo_Bronze_Bump004_Amblem_Bronze_0.geometry} material={materials.Amblem_Bronze} />
      <mesh geometry={nodes.Brake_Pad002_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Brake_Pad_Holder002_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Caliper_Nuts002_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Caliper_Screws002_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Brake_Disc002_Ceramic_Brake_0.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Brake_Disc002_Ceramic_Brake_0001.geometry} material={materials.Ceramic_Brake} />
      <mesh geometry={nodes.Connection_Part002_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Screws002_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws002_Aluminium_0001.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Screws_Holder002_Brake_Rotor_0.geometry} material={materials.Brake_Rotor} />
      <mesh geometry={nodes.Air_Stem003_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Middle_Cap_1002_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Middle_Cap_2002_Metallic_Black_0.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Wheel_Nut002_Aluminium_0.geometry} material={materials.Aluminium} />
      <mesh geometry={nodes.Z06_Rim002_mat_0_Metallic_Black_0001.geometry} material={materials.Metallic_Black} />
      <mesh geometry={nodes.Z06_Rim002_mat_1_Corvette_Yellow_0.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Front_Door_Plastic_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Front_Window_Black_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Rear_Window_Glass_Dark_0.geometry} material={materials.Glass_Dark} />
      <mesh geometry={nodes.Rear_Window_Black_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Rear_Window_Heat_Lines_Window_Defrost_Lines_0.geometry} material={materials.Window_Defrost_Lines} />
      <mesh geometry={nodes.Side_Windows__Back_Rubber_Casing_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Side_Windows__Back_Rubber_Strip_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Side_Window_Rear_Black_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.Side_Windows_Rubber_Divider_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle004_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle009_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle008_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle005_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle006_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle007_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane005_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane006_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane007_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane008_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane009_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle002_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle001_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Circle003_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Plane013_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Wiper_Holder_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.Wiper_Housing_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
      <mesh geometry={nodes.C7R_Carbon_Carbon_0.geometry} material={materials.Carbon} />
      <mesh geometry={nodes.C7R_Texture_and_Alpha_C7R_0.geometry} material={materials['C7.R']} />
    </group>
  )
}

useGLTF.preload('/models/Corvette2.glb')
