/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ModelS.glb 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function ModelS(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/ModelS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_448.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_243.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_258.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_267.geometry} material={materials['back_chrome_light.0']} />
      <mesh geometry={nodes.Object_264.geometry} material={materials.indicator_lr} />
      <mesh geometry={nodes.Object_261.geometry} material={materials.indicator_rr} />
      <mesh geometry={nodes.Object_276.geometry} material={materials.revlight_L} />
      <mesh geometry={nodes.Object_253.geometry} material={materials['hitam.0']} />
      <mesh geometry={nodes.Object_249.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_251.geometry} material={materials['platnomor.1']} />
      <mesh geometry={nodes.Object_255.geometry} material={materials['platnomor.2']} />
      <mesh geometry={nodes.Object_273.geometry} material={materials.left_rear_light} />
      <mesh geometry={nodes.Object_270.geometry} material={materials.right_rear_light} />
      <mesh geometry={nodes.Object_279.geometry} material={materials['tembus_red.0']} />
      <mesh geometry={nodes.Object_410.geometry} material={materials['back_chrome_light.0']} />
      <mesh geometry={nodes.Object_416.geometry} material={materials.foglight_l} />
      <mesh geometry={nodes.Object_413.geometry} material={materials.foglight_r} />
      <mesh geometry={nodes.Object_407.geometry} material={materials['front_black.0']} />
      <mesh geometry={nodes.Object_422.geometry} material={materials.indicator_lf} />
      <mesh geometry={nodes.Object_419.geometry} material={materials.indicator_rf} />
      <mesh geometry={nodes.Object_425.geometry} material={materials['tembus_red.0']} />
      <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.Body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.Body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.Body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.Body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.Body009.geometry} material={materials.Mayan} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.Body012.geometry} material={materials.Silk} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.Body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.Body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.Body016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.Body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.Body018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.Body019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.Object_438.geometry} material={materials['light_pantulan.0']} />
      <mesh geometry={nodes.Object_432.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_441.geometry} material={materials['tembus_red.0']} />
      <mesh geometry={nodes.Object_175.geometry} material={materials['aluminium2.0']} />
      <mesh geometry={nodes.Object_160.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_125.geometry} material={materials['belt.0']} />
      <mesh geometry={nodes.Object_196.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_199.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_202.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_205.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_208.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_128.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_137.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_193.geometry} material={materials['Carpet.0']} />
      <mesh geometry={nodes.Object_211.geometry} material={materials['Carpet_Light.0']} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_151.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_145.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_214.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_178.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_116.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_119.geometry} material={materials['hitam.0']} />
      <mesh geometry={nodes.Object_154.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_157.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_163.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_166.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_113.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_225.geometry} material={materials['LCDs.0']} />
      <mesh geometry={nodes.Object_234.geometry} material={materials['mirror_inside.0']} />
      <mesh geometry={nodes.Object_134.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_122.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_187.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_190.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_181.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_131.geometry} material={materials['satin_red.0']} />
      <mesh geometry={nodes.Object_231.geometry} material={materials['Seat_Leather_white.0']} />
      <mesh geometry={nodes.Object_228.geometry} material={materials['Seat_Leather_white.0']} />
      <mesh geometry={nodes.Object_217.geometry} material={materials['suspensi.0']} />
      <mesh geometry={nodes.Object_219.geometry} material={materials['suspensi.1']} />
      <mesh geometry={nodes.Object_140.geometry} material={materials['suspensi.0']} />
      <mesh geometry={nodes.Object_142.geometry} material={materials['suspensi.1']} />
      <mesh geometry={nodes.Object_222.geometry} material={materials['texture_Buttons.0']} />
      <mesh geometry={nodes.Object_172.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_169.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_184.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['aluminium_light.0']} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['back_chrome_light.0']} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.breaklight_l} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['pantulans.0']} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.right_rear_light} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['black_lights.0']} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.breaklight_l} />
      <mesh geometry={nodes.Object_89.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.foglight_l} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.foglight_r} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.left_front_light} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.right_front_light} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.light_night} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['tembus_red.0']} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.indicator_lf} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.indicator_rf} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['primary.001']} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['chassis.0']} />
      <mesh geometry={nodes.Object_237.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_239.geometry} material={materials['glass.1']} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_295.geometry} material={materials['aluminium2.0']} />
      <mesh geometry={nodes.Object_299.geometry} material={materials['door_lf.0']} />
      <mesh geometry={nodes.Object_301.geometry} material={materials['door_lf.5']} />
      <mesh geometry={nodes.Object_297.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_303.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_283.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_305.geometry} material={materials['mirror_inside.0']} />
      <mesh geometry={nodes.Object_289.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_287.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_312.geometry} material={materials.primary} />
      <mesh geometry={nodes.Object_293.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_309.geometry} material={materials['primary.002']} />
      <mesh geometry={nodes.Object_291.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_285.geometry} material={materials['texture_Buttons.0']} />
      <mesh geometry={nodes.Object_330.geometry} material={materials['aluminium2.0']} />
      <mesh geometry={nodes.Object_332.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_334.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_316.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_324.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_322.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_341.geometry} material={materials.primary} />
      <mesh geometry={nodes.Object_328.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_338.geometry} material={materials['primary.002']} />
      <mesh geometry={nodes.Object_320.geometry} material={materials['primary.004']} />
      <mesh geometry={nodes.Object_326.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_318.geometry} material={materials['texture_Buttons.0']} />
      <mesh geometry={nodes.Object_357.geometry} material={materials['aluminium2.0']} />
      <mesh geometry={nodes.Object_361.geometry} material={materials['door_lf.0']} />
      <mesh geometry={nodes.Object_359.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_363.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_345.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_365.geometry} material={materials['mirror_inside.0']} />
      <mesh geometry={nodes.Object_351.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_349.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_372.geometry} material={materials.primary} />
      <mesh geometry={nodes.Object_355.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_369.geometry} material={materials['primary.002']} />
      <mesh geometry={nodes.Object_353.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_347.geometry} material={materials['texture_Buttons.0']} />
      <mesh geometry={nodes.Object_388.geometry} material={materials['aluminium2.0']} />
      <mesh geometry={nodes.Object_390.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_392.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_376.geometry} material={materials['JUST_BLACK.0']} />
      <mesh geometry={nodes.Object_382.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_380.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_399.geometry} material={materials['primary.002']} />
      <mesh geometry={nodes.Object_386.geometry} material={materials['Plastic.0']} />
      <mesh geometry={nodes.Object_396.geometry} material={materials['primary.002']} />
      <mesh geometry={nodes.Object_384.geometry} material={materials['Putih.0']} />
      <mesh geometry={nodes.Object_378.geometry} material={materials['texture_Buttons.0']} />
      <mesh geometry={nodes.Object_403.geometry} material={materials['glass.0']} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['hub_rb.0']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['hub_rf.0']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['hub_rf.1']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['hub_rb.0']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['hub_rf.0']} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['hub_rf.1']} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['dvorright.0']} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['movsteer_1.0.0']} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_473.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_469.geometry} material={materials['wheels.0']} />
      <mesh geometry={nodes.Object_471.geometry} material={materials['wheels.1']} />
      <mesh geometry={nodes.Object_467.geometry} material={materials['wheels.2']} />
      <mesh geometry={nodes.Object_475.geometry} material={materials['wheels.3']} />
      <mesh geometry={nodes.Object_477.geometry} material={materials['wheels.4']} />
      <mesh geometry={nodes.Object_479.geometry} material={materials['wheels.6']} />
      <mesh geometry={nodes.Object_458.geometry} material={materials['movsteer_1.0.1']} />
      <mesh geometry={nodes.Object_454.geometry} material={materials['wheels.0']} />
      <mesh geometry={nodes.Object_456.geometry} material={materials['wheels.1']} />
      <mesh geometry={nodes.Object_452.geometry} material={materials['wheels.2']} />
      <mesh geometry={nodes.Object_460.geometry} material={materials['wheels.3']} />
      <mesh geometry={nodes.Object_462.geometry} material={materials['wheels.4']} />
      <mesh geometry={nodes.Object_464.geometry} material={materials['wheels.6']} />
    </group>
  )
}

useGLTF.preload('/models/ModelS.glb')
