/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Nissan_Frontier_2022.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Nissan_Frontier_2022.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 9.921, -25.14]} scale={10}>
        <mesh geometry={nodes.frontier_bump_body_01_pivot.geometry} material={materials.frontier_bump_body} position={[0, 0, -0.001]} />
      </group>
      <group position={[0, 13.123, 9.18]} scale={10}>
        <mesh geometry={nodes.body_12_pivot.geometry} material={materials.body} position={[0, 0, 0.003]} />
      </group>
      <group position={[0, 12.991, 9.412]} scale={10}>
        <mesh geometry={nodes.black_matt_54_pivot.geometry} material={materials.black_matt} position={[0, 0, 0]} />
      </group>
      <group position={[-0.706, 12.597, 13.561]} scale={10}>
        <mesh geometry={nodes.black_matt_51_pivot.geometry} material={materials.black_matt} position={[0.001, -0.001, 0]} />
      </group>
      <group position={[0, 4.696, 17.984]} scale={10}>
        <mesh geometry={nodes.black_matt_42_pivot.geometry} material={materials.black_matt} position={[0, 0.002, 0.001]} />
      </group>
      <group position={[0, 10.373, 23.136]} scale={10}>
        <mesh geometry={nodes.black_shiny_23_pivot.geometry} material={materials.black_shiny} position={[0, 0, -0.002]} />
      </group>
      <group position={[0, 10.393, 23.231]} scale={10}>
        <mesh geometry={nodes.black_matt_02_pivot.geometry} material={materials.black_matt} position={[0, 0, -0.001]} />
      </group>
      <mesh geometry={nodes.chrome_13.geometry} material={materials.chrome} position={[0, 5.831, -25.18]} scale={10} />
      <mesh geometry={nodes.glass_08.geometry} material={materials.glass} position={[0, 10.366, -24.738]} scale={10} />
      <mesh geometry={nodes.red_13.geometry} material={materials.red} position={[0, 8.761, -24.41]} scale={10} />
      <mesh geometry={nodes.prox_02.geometry} material={materials.prox} position={[-8.954, 11.288, -19.257]} scale={10} />
      <mesh geometry={nodes.prox_01.geometry} material={materials.prox} position={[8.952, 11.288, -19.257]} scale={10} />
      <mesh geometry={nodes.black_shiny_18.geometry} material={materials.black_shiny} position={[0.001, 11.27, -25.503]} scale={10} />
      <mesh geometry={nodes.black_matt_27.geometry} material={materials.black_matt} position={[-6.153, 9.735, -25.295]} scale={10} />
      <mesh geometry={nodes.glass_12.geometry} material={materials.glass} position={[0, 5.829, -25.19]} scale={10} />
      <mesh geometry={nodes.black_shiny_27.geometry} material={materials.black_shiny} position={[0, 4.515, -20.49]} scale={10} />
      <mesh geometry={nodes.black_shiny_26.geometry} material={materials.black_shiny} position={[0, 5.423, -20.473]} scale={10} />
      <mesh geometry={nodes.silver_13.geometry} material={materials.silver} position={[0, 11.901, -17.038]} scale={10} />
      <mesh geometry={nodes.black_10.geometry} material={materials.black} position={[0, 6.552, -16.521]} scale={10} />
      <mesh geometry={nodes.black_shiny_22.geometry} material={materials.black_shiny} position={[-0.001, 4.385, -20.493]} scale={10} />
      <mesh geometry={nodes.black_matt_39.geometry} material={materials.black_matt} position={[-7.963, 4.135, -12.898]} scale={10} />
      <mesh geometry={nodes.black_matt_38.geometry} material={materials.black_matt} position={[7.963, 4.135, -12.898]} scale={10} />
      <mesh geometry={nodes.silver_15.geometry} material={materials.silver} position={[-7.959, 4.204, -12.811]} scale={10} />
      <mesh geometry={nodes.black_matt_37.geometry} material={materials.black_matt} position={[-8.376, 4.275, -12.416]} scale={10} />
      <mesh geometry={nodes.black_matt_36.geometry} material={materials.black_matt} position={[8.376, 4.275, -12.416]} scale={10} />
      <mesh geometry={nodes.glass_06.geometry} material={materials.glass} position={[0, 17.224, -8.863]} scale={10} />
      <mesh geometry={nodes.r_glass_01.geometry} material={materials.r_glass} position={[0, 17.222, -8.861]} scale={10} />
      <mesh geometry={nodes.glass_05.geometry} material={materials.glass} position={[0, 17.239, -8.754]} scale={10} />
      <mesh geometry={nodes.silver_07.geometry} material={materials.silver} position={[0, 17.239, -8.725]} scale={10} />
      <mesh geometry={nodes.glass_04.geometry} material={materials.glass} position={[0, 17.239, -8.703]} scale={10} />
      <mesh geometry={nodes.silver_06.geometry} material={materials.silver} position={[0, 17.239, -8.669]} scale={10} />
      <mesh geometry={nodes.black_07.geometry} material={materials.black} position={[0, 3.858, 6.119]} scale={10} />
      <mesh geometry={nodes.black_matt_49.geometry} material={materials.black_matt} position={[7.763, 4.278, 16.413]} scale={10} />
      <mesh geometry={nodes.black_matt_48.geometry} material={materials.black_matt} position={[-7.763, 4.278, 16.413]} scale={10} />
      <mesh geometry={nodes.black_matt_32.geometry} material={materials.black_matt} position={[-8.868, 2.046, -15.099]} scale={10} />
      <mesh geometry={nodes.black_matt_31.geometry} material={materials.black_matt} position={[8.868, 2.046, -15.099]} scale={10} />
      <mesh geometry={nodes.black_matt_30.geometry} material={materials.black_matt} position={[-7.754, 3.842, -14.168]} scale={10} />
      <mesh geometry={nodes.black_matt_26.geometry} material={materials.black_matt} position={[7.754, 3.842, -14.168]} scale={10} />
      <mesh geometry={nodes.red_10.geometry} material={materials.red} position={[-8.824, 3.841, -14.061]} scale={10} />
      <mesh geometry={nodes.silver_09.geometry} material={materials.silver} position={[-8.699, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.tire_mat8_01.geometry} material={materials.tire_mat8} position={[7.833, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.silver_16.geometry} material={materials.silver} position={[8.699, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.red_16.geometry} material={materials.red} position={[8.824, 3.841, -14.061]} scale={10} />
      <mesh geometry={nodes.black_matt_40.geometry} material={materials.black_matt} position={[0, 4.161, -13.946]} scale={10} />
      <mesh geometry={nodes.brakes1_03.geometry} material={materials.brakes1} position={[-7.762, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.brakes1_04.geometry} material={materials.brakes1} position={[7.762, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.tire_mat8_04.geometry} material={materials.tire_mat8} position={[-7.633, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.silver_19.geometry} material={materials.silver} position={[-8.499, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.tire_mat8_03.geometry} material={materials.tire_mat8} position={[7.633, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.silver_18.geometry} material={materials.silver} position={[8.499, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.red_18.geometry} material={materials.red} position={[8.624, 3.841, 17.621]} scale={10} />
      <mesh geometry={nodes.orange_01.geometry} material={materials.orange} position={[0, 7.735, 21.435]} scale={10} />
      <mesh geometry={nodes.red_02.geometry} material={materials.red} position={[0, 4.359, 24.807]} scale={10} />
      <mesh geometry={nodes.black_matt_11.geometry} material={materials.black_matt} position={[0.009, 9.589, 24.898]} scale={10} />
      <mesh geometry={nodes.black_matt_12.geometry} material={materials.black_matt} position={[0.01, 6.547, 24.898]} scale={10} />
      <mesh geometry={nodes.black_01.geometry} material={materials.black} position={[0, 10.925, 25.671]} scale={10} />
      <mesh geometry={nodes.black_matt_09.geometry} material={materials.black_matt} position={[0, 9.577, 26.068]} scale={10} />
      <mesh geometry={nodes.black_matt_15.geometry} material={materials.black_matt} position={[0, 9.927, 26.274]} scale={10} />
      <mesh geometry={nodes.black_matt_14.geometry} material={materials.black_matt} position={[0, 9.632, 26.318]} scale={10} />
      <mesh geometry={nodes.black_matt_47.geometry} material={materials.black_matt} position={[-8.668, 2.046, 16.584]} scale={10} />
      <mesh geometry={nodes.black_matt_46.geometry} material={materials.black_matt} position={[8.668, 2.046, 16.584]} scale={10} />
      <mesh geometry={nodes.black_matt_45.geometry} material={materials.black_matt} position={[0, 3.365, 16.816]} scale={10} />
      <mesh geometry={nodes.black_matt_44.geometry} material={materials.black_matt} position={[-7.572, 3.862, 17.51]} scale={10} />
      <mesh geometry={nodes.black_matt_43.geometry} material={materials.black_matt} position={[7.572, 3.862, 17.51]} scale={10} />
      <mesh geometry={nodes.red_21.geometry} material={materials.red} position={[-8.624, 3.841, 17.621]} scale={10} />
      <mesh geometry={nodes.black_shiny_07.geometry} material={materials.black_shiny} position={[0, 9.584, 26.447]} scale={10} />
      <mesh geometry={nodes.silver_01.geometry} material={materials.silver} position={[9.024, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.red_05.geometry} material={materials.red} position={[0, 10.415, -24.139]} scale={10} />
      <mesh geometry={nodes.silver_03.geometry} material={materials.silver} position={[-9.024, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.chrome_02.geometry} material={materials.chrome} position={[0, 17.224, -8.726]} scale={10} />
      <mesh geometry={nodes.black_matt_05.geometry} material={materials.black_matt} position={[0, 8.222, 22.767]} scale={10} />
      <mesh geometry={nodes.silver_04.geometry} material={materials.silver} position={[-8.824, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.silver_02.geometry} material={materials.silver} position={[8.824, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.silver_12_pivot.geometry} material={materials.silver} position={[0, 5.829, -25.189]} scale={10} />
      <mesh geometry={nodes.glass_11_pivot.geometry} material={materials.glass} position={[0, 5.83, -25.179]} scale={10} />
      <mesh geometry={nodes.chrome_12_pivot.geometry} material={materials.chrome} position={[0, 5.83, -25.178]} scale={10} />
      <mesh geometry={nodes.bump_01_pivot.geometry} material={materials.bump} position={[0, 12.75, -24.906]} scale={10} />
      <mesh geometry={nodes.glass_10_pivot.geometry} material={materials.glass} position={[0, 10.352, -24.841]} scale={10} />
      <mesh geometry={nodes.glass_09_pivot.geometry} material={materials.glass} position={[0, 9.031, -24.83]} scale={10} />
      <mesh geometry={nodes.chrome_11_pivot.geometry} material={materials.chrome} position={[0, 10.353, -24.83]} scale={10} />
      <mesh geometry={nodes.plate_01_pivot.geometry} material={materials.plate} position={[-0.006, 5.909, -24.813]} scale={10} />
      <mesh geometry={nodes.silver_11_pivot.geometry} material={materials.silver} position={[0, 9.031, -24.79]} scale={10} />
      <mesh geometry={nodes.black_09_pivot.geometry} material={materials.black} position={[0, 6.94, -24.751]} scale={10} />
      <mesh geometry={nodes.silver_10_pivot.geometry} material={materials.silver} position={[0, 10.367, -24.697]} scale={10} />
      <mesh geometry={nodes.glass_07_pivot.geometry} material={materials.glass} position={[0, 9.025, -24.459]} scale={10} />
      <mesh geometry={nodes.chrome_10_pivot.geometry} material={materials.chrome} position={[0, 9.025, -24.452]} scale={10} />
      <mesh geometry={nodes.chrome_09_pivot.geometry} material={materials.chrome} position={[0, 9.025, -24.419]} scale={10} />
      <mesh geometry={nodes.chrome_14_pivot.geometry} material={materials.chrome} position={[-1.127, 11.494, -25.517]} scale={10} />
      <mesh geometry={nodes.red_15_pivot.geometry} material={materials.red} position={[0, 10.263, -25.47]} scale={10} />
      <mesh geometry={nodes.black_matt_29_pivot.geometry} material={materials.black_matt} position={[0, 11.837, -25.461]} scale={10} />
      <mesh geometry={nodes.black_matt_28_pivot.geometry} material={materials.black_matt} position={[0, 11.67, -25.459]} scale={10} />
      <mesh geometry={nodes.red_14_pivot.geometry} material={materials.red} position={[0, 10.252, -25.41]} scale={10} />
      <mesh geometry={nodes.black_shiny_17_pivot.geometry} material={materials.black_shiny} position={[0, 10.254, -25.409]} scale={10} />
      <mesh geometry={nodes.black_shiny_16_pivot.geometry} material={materials.black_shiny} position={[0, 10.249, -25.388]} scale={10} />
      <mesh geometry={nodes.black_shiny_20_pivot.geometry} material={materials.black_shiny} position={[0, 4.408, -20.493]} scale={10} />
      <mesh geometry={nodes.silver_22_pivot.geometry} material={materials.silver} position={[-5.631, 4.616, -19.842]} scale={10} />
      <mesh geometry={nodes.black_matt_35_pivot.geometry} material={materials.black_matt} position={[0, 12.592, -17.268]} scale={10} />
      <mesh geometry={nodes.bump_02_pivot.geometry} material={materials.bump} position={[0, 12.624, -16.887]} scale={10} />
      <mesh geometry={nodes.black_matt_34_pivot.geometry} material={materials.black_matt} position={[0, 12.405, -16.737]} scale={10} />
      <mesh geometry={nodes.black_matt_33_pivot.geometry} material={materials.black_matt} position={[0, 12.577, -16.466]} scale={10} />
      <mesh geometry={nodes.black_shiny_15_pivot.geometry} material={materials.black_shiny} position={[0, 8.905, -24.336]} scale={10} />
      <mesh geometry={nodes.red_12_pivot.geometry} material={materials.red} position={[0, 10.386, -24.136]} scale={10} />
      <mesh geometry={nodes.r_glass_02_pivot.geometry} material={materials.r_glass} position={[0, 10.343, -24.136]} scale={10} />
      <mesh geometry={nodes.red_11_pivot.geometry} material={materials.red} position={[0, 10.343, -24.124]} scale={10} />
      <mesh geometry={nodes.body_08_pivot.geometry} material={materials.body} position={[0, 5.985, -24.101]} scale={10} />
      <mesh geometry={nodes.glass_13_pivot.geometry} material={materials.glass} position={[0, 10.058, -24.046]} scale={10} />
      <mesh geometry={nodes.black_shiny_21_pivot.geometry} material={materials.black_shiny} position={[0, 4.401, -20.493]} scale={10} />
      <mesh geometry={nodes.silver_14_pivot.geometry} material={materials.silver} position={[7.959, 4.204, -12.811]} scale={10} />
      <mesh geometry={nodes.silver_08_pivot.geometry} material={materials.silver} position={[0, 11.573, -9.311]} scale={10} />
      <mesh geometry={nodes.black_matt_25_pivot.geometry} material={materials.black_matt} position={[0, 9.735, -9.249]} scale={10} />
      <mesh geometry={nodes.body_07_pivot.geometry} material={materials.body} position={[0, 12.185, -9.224]} scale={10} />
      <mesh geometry={nodes.d_glass_02_pivot.geometry} material={materials.d_glass} position={[0, 14.902, -8.949]} scale={10} />
      <mesh geometry={nodes.black_matt_24_pivot.geometry} material={materials.black_matt} position={[0, 14.907, -8.947]} scale={10} />
      <mesh geometry={nodes.black_08_pivot.geometry} material={materials.black} position={[0, 14.902, -8.936]} scale={10} />
      <mesh geometry={nodes.red_08_pivot.geometry} material={materials.red} position={[0, 17.222, -8.853]} scale={10} />
      <mesh geometry={nodes.chrome_08_pivot.geometry} material={materials.chrome} position={[0, 17.224, -8.79]} scale={10} />
      <mesh geometry={nodes.red_07_pivot.geometry} material={materials.red} position={[0, 17.227, -8.747]} scale={10} />
      <mesh geometry={nodes.red_06_pivot.geometry} material={materials.red} position={[0, 17.227, -8.682]} scale={10} />
      <mesh geometry={nodes.black_matt_23_pivot.geometry} material={materials.black_matt} position={[0, 17.222, -8.648]} scale={10} />
      <mesh geometry={nodes.black_matt_22_pivot.geometry} material={materials.black_matt} position={[0, 17.031, -8.36]} scale={10} />
      <mesh geometry={nodes.black_shiny_13_pivot.geometry} material={materials.black_shiny} position={[-0.001, 17.879, -7.341]} scale={10} />
      <mesh geometry={nodes.black_matt_21_pivot.geometry} material={materials.black_matt} position={[0, 14.384, -2.67]} scale={10} />
      <mesh geometry={nodes.body_06_pivot.geometry} material={materials.body} position={[0, 10.937, -1.807]} scale={10} />
      <mesh geometry={nodes.d_glass_01_pivot.geometry} material={materials.d_glass} position={[0, 14.159, 1.479]} scale={10} />
      <mesh geometry={nodes.black_matt_20_pivot.geometry} material={materials.black_matt} position={[0, 14.148, 1.481]} scale={10} />
      <mesh geometry={nodes.chrome_07_pivot.geometry} material={materials.chrome} position={[0, 10.917, 1.505]} scale={10} />
      <mesh geometry={nodes.interior_02_pivot.geometry} material={materials.interior} position={[0, 10.586, 2.19]} scale={10} />
      <mesh geometry={nodes.interior_01_pivot.geometry} material={materials.interior} position={[0.004, 10.47, 2.749]} scale={10} />
      <mesh geometry={nodes.black_06_pivot.geometry} material={materials.black} position={[0, 6.28, 8.153]} scale={10} />
      <mesh geometry={nodes.chrome_06_pivot.geometry} material={materials.chrome} position={[0, 12.976, 8.547]} scale={10} />
      <mesh geometry={nodes.black_matt_53_pivot.geometry} material={materials.black_matt} position={[0, 14.595, 10.363]} scale={10} />
      <mesh geometry={nodes.black_13_pivot.geometry} material={materials.black} position={[0, 14.597, 10.363]} scale={10} />
      <mesh geometry={nodes.d_glass_03_pivot.geometry} material={materials.d_glass} position={[0, 14.626, 10.366]} scale={10} />
      <mesh geometry={nodes.black_matt_52_pivot.geometry} material={materials.black_matt} position={[0, 12.452, 13.528]} scale={10} />
      <mesh geometry={nodes.black_matt_50_pivot.geometry} material={materials.black_matt} position={[8.176, 4.46, 15.967]} scale={10} />
      <mesh geometry={nodes.body_11_pivot.geometry} material={materials.body} position={[0, 8.141, 15.999]} scale={10} />
      <mesh geometry={nodes.silver_21_pivot.geometry} material={materials.silver} position={[-7.759, 4.368, 16.307]} scale={10} />
      <mesh geometry={nodes.silver_20_pivot.geometry} material={materials.silver} position={[7.759, 4.368, 16.308]} scale={10} />
      <mesh geometry={nodes.brakes1_02_pivot.geometry} material={materials.brakes1} position={[-7.962, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.brakes1_01_pivot.geometry} material={materials.brakes1} position={[7.962, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.tire_mat8_02_pivot.geometry} material={materials.tire_mat8} position={[-7.833, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.red_09_pivot.geometry} material={materials.red} position={[8.807, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.black_shiny_14_pivot.geometry} material={materials.black_shiny} position={[8.804, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.black_shiny_19_pivot.geometry} material={materials.black_shiny} position={[-8.804, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.red_17_pivot.geometry} material={materials.red} position={[-8.807, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.red_20_pivot.geometry} material={materials.red} position={[8.607, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.black_shiny_25_pivot.geometry} material={materials.black_shiny} position={[8.604, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.black_shiny_24_pivot.geometry} material={materials.black_shiny} position={[-8.604, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.red_19_pivot.geometry} material={materials.red} position={[-8.607, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.body_10_pivot.geometry} material={materials.body} position={[0, 12.048, 19.403]} scale={10} />
      <mesh geometry={nodes.o_glass_01_pivot.geometry} material={materials.o_glass} position={[0, 7.735, 21.422]} scale={10} />
      <mesh geometry={nodes.orange_02_pivot.geometry} material={materials.orange} position={[0, 7.735, 21.423]} scale={10} />
      <mesh geometry={nodes.body_09_pivot.geometry} material={materials.body} position={[0, 8.184, 21.904]} scale={10} />
      <mesh geometry={nodes.black_12_pivot.geometry} material={materials.black} position={[0, 8.17, 22.649]} scale={10} />
      <mesh geometry={nodes.black_11_pivot.geometry} material={materials.black} position={[0, 10.384, 22.745]} scale={10} />
      <mesh geometry={nodes.black_matt_41_pivot.geometry} material={materials.black_matt} position={[0, 8.163, 22.894]} scale={10} />
      <mesh geometry={nodes.silver_17_pivot.geometry} material={materials.silver} position={[0, 3.933, 23.04]} scale={10} />
      <mesh geometry={nodes.vd_glass_01_pivot.geometry} material={materials.vd_glass} position={[0, 10.838, 23.16]} scale={10} />
      <mesh geometry={nodes.black_shiny_10_pivot.geometry} material={materials.black_shiny} position={[0, 10.838, 23.164]} scale={10} />
      <mesh geometry={nodes.glass_02_pivot.geometry} material={materials.glass} position={[0, 10.377, 23.18]} scale={10} />
      <mesh geometry={nodes.lights_01_pivot.geometry} material={materials.lights} position={[0, 10.404, 23.251]} scale={10} />
      <mesh geometry={nodes.black_matt_13_pivot.geometry} material={materials.black_matt} position={[0, 10.18, 23.668]} scale={10} />
      <mesh geometry={nodes.black_matt_01_pivot.geometry} material={materials.black_matt} position={[0, 4.616, 23.68]} scale={10} />
      <mesh geometry={nodes.glass_01_pivot.geometry} material={materials.glass} position={[0, 6.276, 23.692]} scale={10} />
      <mesh geometry={nodes.chrome_01_pivot.geometry} material={materials.chrome} position={[0, 10.183, 23.924]} scale={10} />
      <mesh geometry={nodes.chrome_03_pivot.geometry} material={materials.chrome} position={[0, 10.178, 24.163]} scale={10} />
      <mesh geometry={nodes.chrome_04_pivot.geometry} material={materials.chrome} position={[0, 7.29, 24.183]} scale={10} />
      <mesh geometry={nodes.chrome_05_pivot.geometry} material={materials.chrome} position={[0, 7.237, 24.229]} scale={10} />
      <mesh geometry={nodes.body_04_pivot.geometry} material={materials.body} position={[0, 7.018, 24.294]} scale={10} />
      <mesh geometry={nodes.black_matt_10_pivot.geometry} material={materials.black_matt} position={[0, 5.901, 24.303]} scale={10} />
      <mesh geometry={nodes.black_03_pivot.geometry} material={materials.black} position={[0, 4.773, 24.36]} scale={10} />
      <mesh geometry={nodes.glass_03_pivot.geometry} material={materials.glass} position={[0, 7.29, 24.388]} scale={10} />
      <mesh geometry={nodes.black_04_pivot.geometry} material={materials.black} position={[0, 6.279, 24.964]} scale={10} />
      <mesh geometry={nodes.silver_05_pivot.geometry} material={materials.silver} position={[0, 4.919, 25.384]} scale={10} />
      <mesh geometry={nodes.black_05_pivot.geometry} material={materials.black} position={[0, 9.518, 25.542]} scale={10} />
      <mesh geometry={nodes.frontier_bump_black_01_pivot.geometry} material={materials.frontier_bump_black} position={[0, 9.943, 25.646]} scale={10} />
      <mesh geometry={nodes.black_02_pivot.geometry} material={materials.black} position={[0, 9.571, 25.663]} scale={10} />
      <mesh geometry={nodes.black_matt_07_pivot.geometry} material={materials.black_matt} position={[0, 6.229, 25.811]} scale={10} />
      <mesh geometry={nodes.black_matt_08_pivot.geometry} material={materials.black_matt} position={[0, 6.279, 25.84]} scale={10} />
      <mesh geometry={nodes.black_matt_16_pivot.geometry} material={materials.black_matt} position={[0, 9.92, 26.193]} scale={10} />
      <mesh geometry={nodes.black_shiny_09_pivot.geometry} material={materials.black_shiny} position={[0, 9.93, 26.332]} scale={10} />
      <mesh geometry={nodes.black_shiny_08_pivot.geometry} material={materials.black_shiny} position={[0, 9.936, 26.363]} scale={10} />
      <mesh geometry={nodes.red_04_pivot.geometry} material={materials.red} position={[0, 9.935, 26.366]} scale={10} />
      <mesh geometry={nodes.plate_02_pivot.geometry} material={materials.plate} position={[-0.006, 6.328, 26.38]} rotation={[Math.PI, 0, Math.PI]} scale={10} />
      <mesh geometry={nodes.red_03_pivot.geometry} material={materials.red} position={[-0.001, 9.95, 26.434]} scale={10} />
      <mesh geometry={nodes.black_shiny_11_pivot.geometry} material={materials.black_shiny} position={[0, 5.412, -20.477]} scale={10} />
      <mesh geometry={nodes.black_matt_18_pivot.geometry} material={materials.black_matt} position={[0, 6.735, -25.062]} scale={10} />
      <mesh geometry={nodes.black_shiny_04_pivot.geometry} material={materials.black_shiny} position={[-7.844, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.black_matt_03_pivot.geometry} material={materials.black_matt} position={[0, 12.743, -25.029]} scale={10} />
      <mesh geometry={nodes.black_matt_19_pivot.geometry} material={materials.black_matt} position={[0, 5.741, -25.069]} scale={10} />
      <mesh geometry={nodes.black_matt_17_pivot.geometry} material={materials.black_matt} position={[0, 10.024, -16.815]} scale={10} />
      <mesh geometry={nodes.body_05_pivot.geometry} material={materials.body} position={[0, 8.286, -16.412]} scale={10} />
      <mesh geometry={nodes.black_shiny_12_pivot.geometry} material={materials.black_shiny} position={[0, 4.174, -20.497]} scale={10} />
      <mesh geometry={nodes.red_01_pivot.geometry} material={materials.red} position={[0, 10.386, -24.139]} scale={10} />
      <mesh geometry={nodes.black_shiny_01_pivot.geometry} material={materials.black_shiny} position={[0, 10.058, -24.039]} scale={10} />
      <mesh geometry={nodes.black_shiny_03_pivot.geometry} material={materials.black_shiny} position={[7.844, 3.842, -14.061]} scale={10} />
      <mesh geometry={nodes.black_shiny_05_pivot.geometry} material={materials.black_shiny} position={[7.644, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.black_shiny_02_pivot.geometry} material={materials.black_shiny} position={[0, 10.893, 23.122]} scale={10} />
      <mesh geometry={nodes.black_shiny_06_pivot.geometry} material={materials.black_shiny} position={[-7.644, 3.842, 17.621]} scale={10} />
      <mesh geometry={nodes.black_matt_04_pivot.geometry} material={materials.black_matt} position={[0, 9.645, 25.854]} scale={10} />
      <mesh geometry={nodes.body_02_pivot.geometry} material={materials.body} position={[0, 10.735, 2.138]} scale={10} />
      <mesh geometry={nodes.black_matt_06_pivot.geometry} material={materials.black_matt} position={[0, 6.721, 1.518]} scale={10} />
      <mesh geometry={nodes.body_01_pivot.geometry} material={materials.body} position={[0, 10.546, 8.523]} scale={10} />
      <mesh geometry={nodes.body_03_pivot.geometry} material={materials.body} position={[0, 17.114, -0.923]} scale={10} />
    </group>
  )
}

useGLTF.preload('/Nissan_Frontier_2022.glb')
